- name: "Scripts | Check folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.scripts"
    state: directory

# - name: "Scripts | Install dependencies"
#   community.general.pacman:
#     name:

- name: "Scripts | Create symlinks"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.scripts"
    state: link
    force: true
