#################
### AUTOSTART ###
#################

exec-once = hyprpaper
exec-once = hypridle
exec-once = sh -c "sleep 1 && quickshell"
exec-once = nm-applet
exec-once = openrgb --startminimized -p purple
exec-once = hyprpm reload -n
exec-once = swaync
exec-once = $HOME/.config/hypr/scripts/define-setup.sh
exec-once = $discord
exec-once = gotify-desktop
exec-once = vicinae server
exec-once = handy --start-hidden
