local apps = require "apps"

hl.on("hyprland.start", function()
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("hyprpm reload -n")
	hl.exec_cmd("nm-applet")
	hl.exec_cmd("openrgb --startminimized -p purple")
	hl.exec_cmd("swaync")
	hl.exec_cmd(apps.discord)
	hl.exec_cmd("gotify-desktop")
	hl.exec_cmd("vicinae server")
	hl.exec_cmd("handy --start-hidden")
	hl.exec_cmd("sh -c 'sleep 1 && quickshell")
end)
