#!/usr/bin/env bash
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

echo -e "${YELLOW}Pushing dotfiles${NC}"
cd $HOME/.config/dotfiles/
git add .
git commit -m "Update dotfiles: $(date)"
git push origin main

echo -e "${YELLOW}Pushing SecondBrain${NC}"
cd $HOME/SecondBrain/
git add .
git commit -m "Update SecondBrain: $(date)"
git push origin main

echo -e "${YELLOW}Pushing Universidad${NC}"
cd $HOME/Universidad/
git add .
git commit -m "Update Universidad: $(date)"
git push origin main
git submodule foreach "git add . && git commit -m 'Update Submodule $path: $(date)' && git push"

echo -e "${YELLOW}Pushing CVNotion${NC}"
cd $HOME/repos/Notion-Sync-CampusVirtual/
git add .
git commit -m "Update Notion-Sync: $(date)"
git push origin main
