#!/bin/sh
xrandr | grep " connected" | awk '{print $1}' |
while read -r word; do
  #if word contains DP
  if [[ $word == DP* ]]; then
    xrandr --output $word --primary --mode 2560x1440 --pos 0x0 --rate 165

  elif [[ $word == HDMI* ]]; then
    xrandr --output $word --mode 1920x1080 --pos 2560x0 --scale 1.15
  fi
done

# reload awesome config
awesome-client "awesome.restart()"
