---
- name: Dotfiles config
  hosts: localhost
  connection: local
  tasks:
    - name: "Sync pacman"
      become: true
      ansible.builtin.shell:
        cmd: "sudo pacman -Syy"

    - name: Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ default_roles }}"
      tags:
        - always
