#!/usr/bin/env bash
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

echo -e "${YELLOW}Pulling dotfiles${NC}"
cd $HOME/.config/dotfiles/
git pull

# echo "Pulling SecondBrain"
# cd $HOME/SecondBrain/
# git pull

echo -e "${YELLOW}Pulling Universidad${NC}"
cd $HOME/Universidad/
git pull

echo -e "${YELLOW}Pulling CVNotion${NC}"
cd $HOME/repos/Notion-Sync-CampusVirtual/
git pull
