#!/usr/bin/env bash
# Dotfiles Universidad SecondBrain
echo "Pulling dotfiles"
cd $HOME/.config/dotfiles/
git pull

echo "Pulling SecondBrain"
cd $HOME/SecondBrain/
git pull

echo "Pulling Universidad"
cd $HOME/Universidad/
git pull
