#!/usr/bin/env bash
# Dotfiles Universidad SecondBrain

printf '\nPushing dotfiles\n'
cd $HOME/.config/dotfiles/
git add .
git commit -m "Update dotfiles: $(date)"
git push origin main

# cd $HOME/SecondBrain/
# git add .
# git commit -m "Update SecondBrain: $(date)"
# git push origin main

printf "\nPushing Universidad\n"
cd $HOME/Universidad/
git add .
git commit -m "Update Universidad: $(date)"
git push origin main

printf "\nPushing CVNotion\n"
cd $HOME/repos/Notion-Sync-CampusVirtual/
git add .
git commit -m "Update Notion-Sync: $(date)"
git push origin main
