#!/usr/bin/env bash
GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo -e "${GREEN}Pushing dotfiles${NC}"
cd $HOME/.config/dotfiles/
git add .
git commit -m "Update dotfiles: $(date)"
git push origin main

# cd $HOME/SecondBrain/
# git add .
# git commit -m "Update SecondBrain: $(date)"
# git push origin main

echo -e "${GREEN}Pushing Universidad${NC}"
cd $HOME/Universidad/
git add .
git commit -m "Update Universidad: $(date)"
git push origin main

echo -e "${GREEN}Pushing CVNotion${NC}"
cd $HOME/repos/Notion-Sync-CampusVirtual/
git add .
git commit -m "Update Notion-Sync: $(date)"
git push origin main
