#!/usr/bin/env bash
notify-send "Syncing SecondBrain"
REPO_DIR=~/SecondBrain/
MESSAGE="Update SecondBrain - $(date)"
GIT=`which git`
cd ${REPO_DIR}
${GIT} add .
${GIT} commit -m "${MESSAGE}"
${GIT} push
