#!/usr/bin/env bash
set -euo pipefail

# Script setup básico para módulo
if [ ! -d ~/.tmux/plugins/tpm ]; then
    git clone "https://github.com/tmux-plugins/tpm" ~/.tmux/plugins/tpm
fi

rm -rf  $HOME/.config/tmux
ln -snf $CONFIG_DIR $HOME/.config/tmux
