#!/usr/bin/env bash
set -euo pipefail

# Script setup básico para módulo
if [ ! -d ~/.tmux/plugins/tpm ]; then
    git clone "https://github.com/tmux-plugins/tpm" ~/.tmux/plugins/tpm
fi

rm -rf  $HOME/.config/tmux
ln -snf $CONFIG_DIR $HOME/.config/tmux

# Instalar plugins de tmux
if command -v tmux &> /dev/null && [ -x ~/.tmux/plugins/tpm/scripts/install_plugins.sh ]; then
    ~/.tmux/plugins/tpm/scripts/install_plugins.sh
fi

# Recargar configuración si tmux está corriendo
if tmux info &> /dev/null; then
    tmux source-file ~/.config/tmux/tmux.conf
fi
