require('plugins.harpoon')
require('plugins.telescope')
require('plugins.catppuccin')
require('plugins.nvim-cmp')
require('plugins.lspconfig')
require('plugins.treesitter')
require('plugins.lualine')
require('plugins.nvim-tree')
require('plugins.custom')
require('plugins.copilot')
require('plugins.gitsigns')
require('plugins.zen')
require('plugins.vim-fugitive')
-- require('plugins.todo-comments')
