#!/bin/bash

if ! which awesome &> /dev/null; then
		gum spin --spinner dot --title "Checking for $(gum style --foreground 212 'yay')" -- 
    yay -S rofi wmctrl visual-studio-code-bin firefox solaar bluez bluez-utils blueberry networkmanager jq network-manager-applet picom autorandr playerctl pamixer brightnessctl ranger zathura tlp tlpui gpick pavucontrol pipewire-alsa pipewire-pulse pipewire-audio nodejs upower luarocks &&
    sudo luarocks install lyaml &&
    sudo luarocks install dkjson &&
    yay -S awesome-git
fi

if ! which sp -v &> /dev/null; then
		git clone https://gist.github.com/fa6258f3ff7b17747ee3.git /tmp/fa6258f3ff7b17747ee3
		cd /tmp/fa6258f3ff7b17747ee3
		chmod +x sp
		sudo cp ./sp /usr/local/bin/
fi

ln -sfn $FILES_DIR $HOME/.config/awesome
