#!/bin/bash

ln -snf $FILES_DIR $HOME/.config/systemd/user/myservices

for service in $HOME/.config/systemd/user/myservices/*.service; do
	systemctl --user enable --now $HOME/.config/systemd/user/myservices/$(basename $service)
done
