#!/bin/bash

rm -rf $HOME/.config/wireplumber

if [ -z "(which pipewire)" ]; then
	yay -S pipewire pipewire-pulse pipewire-jack pipewire-alsa 
fi

if [ -z "(which wirepluber)" ]; then
	yay -S wireplumber 
fi
ln -snf $FILES_DIR $HOME/.config/wireplumber

systemctl --user restart pipewire
