#!/bin/bash

yay -S zsh bat lsd

# Install oh-my-zsh
if [ ! -d "$HOME/.oh-my-zsh/" ]; then
		sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

ln -snf $FILES_DIR/.zshrc $HOME/.zshrc
ln -snf $FILES_DIR/.Xresources $HOME/.Xresources

if [ -d "$HOME/.oh-my-zsh" ]; then
	ln -snf $FILES_DIR/custom $HOME/.oh-my-zsh/custom
fi
