#!/usr/bin/env bash
set -euo pipefail

# Script setup básico para módulo

if [ ! -d "$HOME/.oh-my-zsh/" ]; then
    RUNZSH=no sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    chsh -s $(which zsh)
fi

rm -rf "$HOME/.oh-my-zsh/custom"
ln -sf "$CONFIG_DIR/custom" "$HOME/.oh-my-zsh/custom"

ln -sf "$CONFIG_DIR/.zshrc" "$HOME/.zshrc"
ln -sf "$CONFIG_DIR/.Xresources" "$HOME/.Xresources"
