#!/usr/bin/env bash
set -euo pipefail
source $DOTFILES_DIR/core/logger

# Script setup básico para módulo
sudo systemctl enable docker.service
sudo systemctl start docker.service

sudo groupadd -f docker
sudo usermod -aG docker $USER

log_info "Docker configurado. Necesitas cerrar sesión y volver a entrar para que los cambios de grupo tomen efecto."
log_info "Alternativamente, ejecuta: newgrp docker"
