#!/usr/bin/env bash
set -euo pipefail

# Script setup básico para módulo
sudo systemctl enable docker.service
sudo systemctl start docker.service

sudo groupadd -f docker
sudo usermod -aG docker $USER
newgrp docker
