- name: "Kitty | Install"
  community.general.pacman:
    name: kitty
    state: latest
  become: true

- name: "Kitty | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/kitty"
    state: directory

- name: "Kitty | Create symlink"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/kitty"
    state: link
    force: true
