#!/bin/bash
DATA=$(bw get item "notion-sync")
NOTION_TOKEN=$(echo $DATA | jq -r ".fields[1].value")
DATABASE_ID=$(echo $DATA | jq -r '.fields[2].value')

RESPONSE=$(curl -s -X POST 'https://api.notion.com/v1/databases/'"$DATABASE_ID"'/query' \
  -H 'Authorization: Bearer '"$NOTION_TOKEN"'' \
  -H 'Notion-Version: 2022-06-28' \
  -H "Content-Type: application/json" \
--data '{
  "filter": {
    "and" : [
      {
        "property": "Fecha",
        "date": {
          "on_or_after": "'$(date +"%Y-%m-%d")'"
        }
      },
      {
        "or": [
          {
            "property": "From",
            "select": {
              "equals": "CV"
            }
          },
          {
            "property": "Tipo",
            "select": {
              "equals": "Examen"
            }
          }
        ]
      }
    ]
  },
    "sorts": [
      {
        "property": "Falta...",
        "direction": "ascending"
      }
    ]
  }')

# echo $RESPONSE | jq -c '[.results[] | { "title": .properties["Nombre de tarea"].title[].plain_text, "date": (.properties["Fecha"].date.start | split("T") | ( .[0] | strptime("%Y-%m-%d") | strftime("%d-%m-%Y")) + " " + (.[1] | split(".") | .[0])), "status": .properties["Resumen"].formula.string}]'

echo $RESPONSE | jq -c '[.results[] | { "title": .properties["Nombre de tarea"].title[].plain_text, "date": (.properties["Fecha"].date.start | split("T") | ( .[0] | strptime("%Y-%m-%d") | strftime("%d %b")) + " " + (.[1] | split(".") | .[0] | split(":") | .[0] + ":" + .[1])), "status": .properties["Resumen"].formula.string}]'
