#!/usr/bin/env bash
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

until ping -c1 google.com; do sleep 5; done

echo -e "${YELLOW}Pulling dotfiles${NC}"
cd $HOME/.dotfiles
git pull

echo -e "${YELLOW}Pulling Universidad${NC}"
cd $HOME/Universidad/
git pull
git submodule foreach "git checkout main; git pull"
