monitor.alsa.rules = [

  # BenQ EX2710Q (salida NVIDIA Pro Audio 8) → prioridad alta
  {
    matches = [
      {
        media.class = "Audio/Sink"
        node.name = "alsa_output.pci-0000_01_00.1.pro-output-8"
      }
    ]
    actions = {
      update-props = {
        priority.session = 2000
      }
    }
  }

]
