monitor.alsa.rules = [
  {
    matches = [
      {
        # BenQ EX2710Q when the NVIDIA card uses Pro Audio.
        node.name = "alsa_output.pci-0000_01_00.1.pro-output-8"
      }
    ]
    actions = {
      update-props = {
        node.nick = "Monitor Principal"
        node.description = "Monitor Principal"
      }
    }
  }
]

# monitor.alsa.rules = [
#   {
#     matches = [
#       {
#         # Matches all sources
#         node.name = "~alsa_output.*loop*"
#       }
#     ]
#     actions = {
#       update-props = {
#         node.disabled = true
#       }
#     }
#   },
# 	{
# 		matches = [
# 			{
# 				# Matches all sources
# 				node.name = "alsa_output.usb-Logitech_PRO_X_Wireless_Gaming_Headset-00.analog-stereo"
# 			}
#     ]
#     actions = {
#       update-props = {
#         node.description = "Logitech PRO X"
#       }
#     }
# 	},
# 	{
# 		matches = [
# 			{
# 				# Matches all sources
# 				node.name = "alsa_input.usb-Logitech_PRO_X_Wireless_Gaming_Headset-00.mono-fallback"
# 			}
# 		]
# 		actions = {
# 			update-props = {
# 				node.description = "Logitech PRO X (Mic)"
# 			}
# 		}
# 	},
# ]
