#!/usr/bin/env bash
set -euo pipefail

# Script setup básico para módulo
DEST=$HOME/.config/hypr

rm -rf $DEST

ln -snf $CONFIG_DIR $DEST

# Install plugins

if ! hyprpm list plugins | grep -q "split-monitor-workspaces"; then
    hyprpm add https://github.com/Duckonaut/split-monitor-workspaces
    hyprpm enable split-monitor-workspaces
else
    hyprpm update
fi

hyprpm reload # Reload the plugins
