- name: "Neovim | Install dependencies"
  become: true
  community.general.pacman:
    name:
      - cmake
      - curl
      - pkg-config
      - libtool
      - unzip
      - ripgrep
      - xclip
    state: latest

- name: "Neovim | Install"
  become: true
  community.general.pacman:
    name: neovim
    state: latest

- name: "Neovim | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory

- name: "Neovim | Create symlink"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link
    force: true

